Repository FrancescoXX/4c-site, pull requests merged in 2021-10, with the labels that each got.

#70 Fix contributors script
  scripts/update_contributors.js
Labels: hacktoberfest, hactoberfest-accepted

#68 Update README with Contributing and License
  README.md
Labels: hacktoberfest, hactoberfest-accepted

#73 Contributor text changed to button :)
  components/Header.js
  package-lock.json
Labels: hacktoberfest, hactoberfest-accepted

#72 Added discord colour on hover to community button and made it target …
  content/homepage.js
  styles/button.css
Labels: hacktoberfest, hactoberfest-accepted

#74 title and description seo
  pages/index.js
Labels: hacktoberfest, hactoberfest-accepted

#86 changed to button
  components/Contributors.jsx
Labels: hacktoberfest, hactoberfest-accepted

#88 Disable hover animation if prefers-reduced-motion is true
  components/Contributors.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#89 Duplicate main elements removed from contributors page.
  components/Contributors.jsx
  pages/contributors.js
Labels: hacktoberfest, hacktoberfest-accepted

#91 add bug-report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: hacktoberfest

#65 feat: added google analytics via tag manager
  pages/_app.js
  pages/_document.js
  utils/gtm.js
Labels: hacktoberfest, hacktoberfest-accepted

#112 removed the button of contributors in the page contributors
  components/Header.js
Labels: hacktoberfest, hacktoberfest-accepted
