Repository FrancescoXX/4c-site, pull requests merged in 2022-10, with the labels that each got.

#187 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#224 [FEATURE] FAQ Capitalize
  components/Header.js
  scripts/update_contributors.js
Labels: invalid

#234 Added font
  BRAND.md
Labels: invalid

#259 [FEATURE] FAQ page structure done
  content/faq.json
  package-lock.json
  pages/Faq.js
Labels: hacktoberfest

#266 Active member name changed
  components/ActiveMembers.js
  components/Header.js
  pages/activeMembers.js
Labels: hacktoberfest, hacktoberfest-accepted

#305 Update projects.json
  content/projects.json
Labels: invalid
